#!/bin/sh

# will, one by one, list docker volumes and remove them.
# meaning: all containers have to be rebuilt and data will be lost


read -p "Do you really want to remove all docker volumes on your system? " -n 1 -r
echo 
if [[ $REPLY =~ ^[Yy]$ ]]
then
    docker volume ls -q | xargs docker volume rm
    echo
    echo "done. the list of volumes is now:"
    echo
    docker volume ls
fi